/* eslint-disable prettier/prettier */
// This file was generated by a custom prisma generator, do not edit manually.
export const Role = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;

export type Role = (typeof Role)[keyof typeof Role];

export const ECountryCodeP = {
  MY: "MY",
  SG: "SG",
} as const;

export type ECountryCodeP = (typeof ECountryCodeP)[keyof typeof ECountryCodeP];

export const CompanyType = {
  PRIVATE_LIMITED: "PRIVATE_LIMITED",
  SOLE_PROPRIETORSHIP: "SOLE_PROPRIETORSHIP",
  PARTNERSHIP: "PARTNERSHIP",
} as const;

export type CompanyType = (typeof CompanyType)[keyof typeof CompanyType];
